dist: trusty
language: go
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - openjdk-8-jdk
    - bazel
install: echo '{Fast, Correct} - Choose two'
script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --test_output=errors \
      --experimental_repository_cache="$HOME/.cache/bazel_repository_cache" \
      //...
