language: go
go_import_path: github.com/kyleconroy/protocompat
cache:
  directories:
    - $HOME/.bzrepos
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel
os: linux
dist: trusty
script:
- bazel --batch --bazelrc=.test-bazelrc test --experimental_repository_cache="$HOME/.bzrepos" --test_arg="-test.short" //...
