dist: trusty
language: go
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - openjdk-8-jdk
    - bazel
install: echo 'Install'
script: bazel test ...
