language: go
go_import_path: github.com/kyleconroy/protocompat

cache:
  directories:
    - $HOME/.bzrepos

os: linux
dist: trusty
sudo: required

before_script:
- wget "https://storage.googleapis.com/bazel-apt/pool/jdk1.8/b/bazel/bazel_0.5.2_amd64.deb"
- sudo dpkg --force-all -i bazel_0.5.2_amd64.deb

script:
- bazel --batch --bazelrc=.test-bazelrc test --experimental_repository_cache="$HOME/.bzrepos" --test_arg="-test.short" //...
